version: '2'
services:
  web:
    build:
      context: ..
      dockerfile: './docker/not-so-dockerfile.Dockerfile'
    command: "node index.js"
    ports:
      - "1000"
      - "2000"
      - "3000"
      - "4000"
